### ISSUE TITLE
Undefined  index: mage_catalog_category_entity

### ISSUE THREAD

**Issue by SRaffiou** [hipay/hipay-fullservice-sdk-magento2#116]
### Context

- Migration from Magento 2.1.9 to Magento 2.3
- Hipay Module 1.3.4
- Since the migration only Magento core modules are enabled
- PHP 7.1.19

### Issue

- `bin/magento setup:upgrade` does not work and display the error message
> Undefined  index: mage_catalog_category_entity in path_to_ptoject/vendor/magento/framework/Setup/Declaration/Schema/Db/SchemaBuilder.php on line 155.

### Full Description

Good Morning,

I'm trying to migrate one of our project from magento 2.1.9 to 2.3.

I'm having a weird error related to _**hipay_cart_mapping_categories**_ when trying to launch the command _**bin/magento setup:upgrade**_.

> Undefined index: mage_catalog_category_entity in path_to_ptoject/vendor/magento/framework/Setup/Declaration/Schema/Db/SchemaBuilder.php on line 155.

**mage_catalog_category_entity** is referenced in _**\HiPay\FullserviceMagento\Setup\UpgradeSchema**_ as a foreign key target. There is not table with name **mage_catalog_category_entity** , did you want to target **catalog_category_entity**  instead ?

It seems Magento 2.3 is making additionnal checks to validate database integrity.

Please find below some information that can help you detect / resolve the incident.

`\Magento\Setup\Console\Command\UpgradeCommand::execute `
`\Magento\Setup\Model\Installer::installSchema`
`\Magento\Setup\Model\Installer::declarativeInstallSchema`
`\Magento\Setup\Model\DeclarationInstaller::installSchema`
`\Magento\Framework\Setup\Declaration\Schema\SchemaConfig::getDbConfig`
_**`\Magento\Framework\Setup\Declaration\Schema\Db\SchemaBuilder::build`**_
`\Magento\Framework\Setup\Declaration\Schema\Db\SchemaBuilder::processReferenceKeys`
`\Magento\Framework\Setup\Declaration\Schema\Db\MySQL\DbSchemaReader::readReferences`
_**`\Magento\Framework\Setup\Declaration\Schema\Db\MySQL\DbSchemaReader::getCreateTableSql`**_

Best Regards

**Comment by legithubdeaymeric** [comment]
Hello,

You are right, there is indeed an error in the file **UpgradeShema** on the name of the entity which is filled with the prefix "mage".
However, the constraint in the database is correct. The error should probably come from the static analysis that is done by magento on the upgrade system.

However, we can not reproduce the warning during a version upgrade or during a module installation on a magento 2.3 probably due to an error reporting configuration but we are not sure.

We will therefore make a release to correct this problem.

To quickly unblock you can directly edit the two references in the file or apply the patch.
https://github.com/hipay/hipay-fullservice-sdk-magento2/commit/d101181ed77b75bcbab4b4ad5364d2436f0f1de9

**Comment by SRaffiou** [comment]
Hello,

I updated the database constraint and it fixed the issue.

Thanks you for the new version.

Best Regards,
